//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using UnityEngine;

namespace AssemblyCSharp
{
	public class GraphImport
	{
		public static Graph ReadGraphFromFile(TextAsset filepath)
		{
			Graph graph = new Graph();

			string[] file = filepath.text.Split("\n"[0]);

			foreach(string s in file)
			{
				string[] values = s.Split(","[0]);

				if (values[0] == "N")
				{
					graph.AddNode(Convert.ToSingle(values[1]), Convert.ToSingle(values[2]), Convert.ToSingle(values[3]));
				}
				else if (values[0] == "A")
				{
					graph.AddArc((Node)graph.Nodes[Convert.ToInt32(values[1])], (Node)graph.Nodes[Convert.ToInt32(values[2])],1);
				}

			}
			return graph;
		}
	}
}

