// This enum was generated by Dialoguer
public enum DialoguerDialogues{
	GuardDialogue = 0,
	DaddyDialogue = 1,
	LibrarianDialogue = 2,
	FluteDialogue = 3,
	ChildMomDialogue = 4,
	LeaveDialogue = 5,
	StayDialogue = 6,
	LeavewithChildDialogue = 7,
	DecisionDialogue = 8,
	LeavenoResidentDialogue = 9,
	LeaveEarlyDialogue = 10,
}
